apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-db-pv
  namespace: oracle
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"
  persistentVolumeReclaimPolicy: Retain
