apiVersion: v1
kind: Pod
metadata:
  namespace: oracle
  name: oracle-db
  labels:
    app: oracle-db
spec:
  containers:
    - name: oracle-db
      image: lomank/oracle-db:1.0.0
      ports:
        - containerPort: 27017
      envFrom:
        - configMapRef:
            name: oracle-config
      volumeMounts:
        - mountPath: /data/db
          name: oracle-db-storage
  volumes:
    - name: oracle-db-storage
      persistentVolumeClaim:
        claimName: oracle-db-pvc
